name: Trigger Pali Dhatu App Build
on:
  push:
    branches:
      - main
    paths:
      - 'data/**' # ทำงานเมื่อมีการแก้ไฟล์ใน folder data

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in pali-dhatu-app
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }} # ต้องเพิ่ม secret GH_PAT ใน repo theonlyone ด้วยเช่นกัน
          repository: Kanjin22/pali-dhatu-app
          event-type: data-updated
